[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://studio-backend-production.up.railway.app"
  NEXT_PUBLIC_WS_URL = "wss://studio-backend-production.up.railway.app"

[[redirects]]
  from = "/api/*"
  to = "https://studio-backend-production.up.railway.app/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"